# Generated by Django 5.2 on 2025-05-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.CharField(editable=False, max_length=255, unique=True)),
                ('customer', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('business', 'Business')], max_length=20)),
                ('issue_date', models.DateField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('draft', 'Draft'), ('declined', 'Declined'), ('close', 'Close'), ('open', 'Open')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
