# Generated by Django 5.2 on 2025-05-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('business', 'Business')], max_length=20)),
                ('customer', models.CharField(max_length=255)),
                ('quotation_type', models.CharField(choices=[('pos', 'Pos'), ('invoice', 'Invoice')], max_length=20)),
                ('quotation_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
