# Generated by Django 5.2 on 2025-05-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('workspace', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_time', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
