# Generated by Django 5.2 on 2025-05-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retainer_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('business', 'Business')], max_length=20)),
                ('issue_date', models.DateField()),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
