# Generated by Django 5.2 on 2025-05-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select')], max_length=20)),
                ('module', models.CharField(help_text='The name of the module this field is associated with.', max_length=100)),
                ('rule', models.TextField(blank=True, help_text='Validation rule or condition for this custom field.')),
            ],
        ),
    ]
