# Generated by Django 5.2 on 2025-05-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivestormMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('owner_name', models.CharField(max_length=100)),
                ('invites', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('session_count', models.IntegerField()),
                ('scheduling_status', models.CharField(choices=[('ended', 'Ended'), ('not scheduled', 'Not Scheduled'), ('not started', 'Not Started')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
