# Generated by Django 5.2 on 2025-05-13 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('post', 'Post'), ('message', 'Message'), ('comment', 'Comment')], max_length=20)),
                ('sender_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('facebook_id', models.CharField(help_text='Facebook post/message/comment ID', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(help_text='Facebook post ID', max_length=100, unique=True)),
                ('page_name', models.CharField(help_text='Name of the Facebook page', max_length=255)),
                ('message', models.TextField(help_text='Text content of the post')),
                ('link', models.URLField(blank=True, help_text='Optional link shared in the post')),
                ('image_url', models.URLField(blank=True, help_text='Optional image URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
