# Generated by Django 5.2 on 2025-05-03 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(help_text='Facebook post ID', max_length=100, unique=True)),
                ('page_name', models.CharField(help_text='Name of the Facebook page', max_length=255)),
                ('message', models.TextField(help_text='Text content of the post')),
                ('link', models.URLField(blank=True, help_text='Optional link shared in the post')),
                ('image_url', models.URLField(blank=True, help_text='Optional image URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
