# Generated by Django 5.2 on 2025-05-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_number', models.CharField(default='#RENTALO000001', max_length=20, unique=True)),
                ('customer', models.CharField(max_length=100)),
                ('rental_type', models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
