# Generated by Django 5.2 on 2025-05-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='media/meeting_reports/'),
        ),
    ]
