# Generated by Django 5.2 on 2025-05-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='date',
        ),
        migrations.AlterField(
            model_name='billrecord',
            name='bill_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='billrecord',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='creditnotes',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='debitnotes',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='to_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymenetrecord',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
