# Generated by Django 5.2 on 2025-05-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_revenue_date_remove_transfer_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymenetRecord',
            new_name='PaymentRecord',
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_period',
            field=models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly'), ('half-yearly', 'half-yearly'), ('quarterly', 'quarterly')], default='monthly', max_length=20),
        ),
    ]
