# Generated by Django 5.2 on 2025-05-02 12:50

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(default=items.models.generate_sku, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/products/')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, help_text='Tax %', max_digits=5)),
                ('category', models.CharField(max_length=100)),
                ('unit', models.CharField(help_text='e.g. pcs, kg, liter', max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital'), ('service', 'Service')], max_length=20)),
            ],
        ),
    ]
