# Generated by Django 5.2 on 2025-05-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_or_folder_name', models.CharField(max_length=255, verbose_name='File / Folder Name')),
                ('related', models.CharField(blank=True, max_length=255, null=True, verbose_name='Related')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
