# Generated by Django 5.2 on 2025-05-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_no', models.CharField(max_length=50, unique=True, verbose_name='No')),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords', null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contacts_found', models.PositiveIntegerField(default=0, verbose_name='Contacts Found')),
            ],
        ),
    ]
