# Generated by Django 5.2 on 2025-05-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('invites', models.CharField(help_text='Comma-separated list of invitee emails or names', max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('waiting', 'Waiting')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
