# Generated by Django 5.2 on 2025-05-05 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('waiting', 'Waiting')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invites', models.ManyToManyField(related_name='zoom_meeting_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
