# Generated by Django 5.2 on 2025-05-03 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dm', 'Direct Message'), ('comment', 'Comment'), ('mention', 'Mention')], max_length=20)),
                ('username', models.CharField(help_text='Instagram username', max_length=255)),
                ('content', models.TextField()),
                ('instagram_id', models.CharField(help_text='Instagram post/comment/message ID', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
