# Generated by Django 5.2 on 2025-05-03 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(help_text='Instagram post ID', max_length=100, unique=True)),
                ('username', models.CharField(help_text='Instagram account username', max_length=255)),
                ('caption', models.TextField(blank=True, help_text='Text caption of the post')),
                ('image_url', models.URLField(blank=True, help_text='Direct link to the image or video')),
                ('post_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('reel', 'Reel'), ('carousel', 'Carousel')], default='image', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.BooleanField(default=False)),
                ('scheduled', models.BooleanField(default=False)),
            ],
        ),
    ]
