# Generated by Django 5.2 on 2025-05-06 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserMGMT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='UserMGMT.role'),
        ),
    ]
