# Generated by Django 5.2 on 2025-05-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserMGMT', '0002_remove_role_name_remove_role_user_role_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='name',
        ),
    ]
