# Generated by Django 5.2 on 2025-05-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserMGMT', '0002_alter_userrole_unique_together_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
