# Generated by Django 5.2 on 2025-05-12 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserMGMT', '0003_user_is_email_verified_userrole_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='workspace_name',
            new_name='username',
        ),
    ]
