# Generated by Django 5.2 on 2025-05-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserMGMT', '0004_rename_workspace_name_user_username'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='RoleModelPermission',
        ),
    ]
