# Generated by Django 5.2 on 2025-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('contract', 'Contract'), ('remote', 'Remote'), ('internship', 'Internship'), ('temporary', 'Temporary')], max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('apply_link', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
