"""
Django settings for Dash project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2da&1r3x5e4z95a4aaz%aj@$z$#d!d#r^bno&e%e%y5ay5lok2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'Dashboard',
    'UserMGMT',
    'items',
    'proposal',
    'retainer',
    'invoice',
    'purchases',
    'quotation',
    'projects',
    'accounts',
    'doubleentry',
    'hrm',
    'recruitment',
    'jobsearch',
    'biometricattendance',
    'procurement',
    'pos',
    'crm',
    'formbuilder',
    'sales',
    'whatsapp',
    'facebook',
    'instagram',
    'zulip',
    'youtube',
    'vcard',
    'LMS',
    'entertainment',
    'moviebooking',
    'waterpark',
    'coworkingspace',
    'dietnutrition',
    'SecurityGuard',
    'SportsClub',
    'GardenMGMT',
    'LockerSafe',
    'EventMGMT',
    'HotelRooms',
    'Rotas',
    'Comission',
    'CMMS',
    'SchoolInstitute',
    'MusicInstitute',
    'Childcare',
    'DrivingSchool',
    'GymMGMT',
    'Construction',
    'Fleet',
    'vehicleTrade',
    'vehicleBooking',
    'CarDealership',
    'Agriculture',
    'LegalCase',
    'TourTravel',
    'Insurance',
    'Courier',
    'Freight',
    'GarageWorkshop',
    'NewsPaper',
    'PropertyMGMT',
    'ElderlyCare',
    'Hospital',
    'OpticalEyeCare',
    'MedicalLab',
    'Pharmacy',
    'BeautySpa',
    'Bookings',
    'Beverages',
    'Facilities',
    'Parking',
    'SupportTicket',
    'TailoringFasionDesign',
    'Restaurant',
    'DairyCattle',
    'WasteMGMT',
    'Consignment',
    'Cleaning',
    'MobileService',
    'VehicleInspection',
    'MachineRepair',
    'Repair',
    'AI',
    'Laundary',
    'Catering',
    'Rental',
    'SalesAgent',
    'SalesForce',
    'Contract',
    'Documents',
    'GoogleDocs',
    'CustomField',
    'WooCommerce',
    'Shopify',
    'Indiamart',
    'Sage',
    'Asana',
    'Inventory',
    'Assets',
    'Requests',
    'FixEquipments',
    'Hubspot',
    'Calendar',
    'MeetingHub',
    'Appointment',
    'Portfolio',
    'ResumeBuilder',
    'Reminder',
    'Workflow',
    'GoogleSheet',
    'Spreadsheet',
    'GoogleLeads',
    'InnovationCenter',
    'BusinessMapping',
    'RoadmapCentral',
    'Planning',
    'InternalKnowledge',
    'CallHub',
    'QueueMGMT',
    'VideoHub',
    'PhotoStudio',
    'FileSharing',
    'Feedback',
    'Newsletter',
    'EmailBox',
    'Sendinblue',
    'OneNotes',
    'Notes',
    'TeamWorkload',
    'QuizMGMT',
    'PrettyCash',
    'Trello',
    'ToDo',
    'Visitors',
    'HelpDesk',
    'ActivityLog',
    'GoogleMeet',
    'GotoMeeting',
    'ZoomMeeting',
    'OutlookCalendar',
    'SideMenuBuilder',
    'TimeTracker',
    'TimeSheet',
    'WhereByMeeting',
    'ZohoMeeting',
    'Messenger',
    'LiveStormMeeting',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Dash.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Dash.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type

# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'UserMGMT.User'
